version: '3.8'

services:
  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3001}:3001"
    depends_on:
      - mongodb
    environment:
      PORT: "${API_PORT:-3001}"
      MONGO_URL: "mongodb://mongodb:27017"
    volumes:
      - ./Server:/usr/src/app
      - /usr/src/app/node_modules
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.50'

  frontend:
    build:
      context: ./App
      dockerfile: Dockerfile
    environment:
      - CLIENT_PORT=${CLIENT_PORT:-3000}
    ports:
      - "${CLIENT_PORT:-3000}:3000"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.50'

  mongodb:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./Server/volume/mongo:/data/db
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.50'

volumes:
  mongo-data: